on:
  pull_request:
    branches:
      - master
    types:
      - closed

name: deployment

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest

    - name: "Create stack"
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
        file: docker-compose.yml
